### ISSUE TITLE
run.sh file in examples/virtual/diamond folder is outdated.

### ISSUE THREAD

**Issue by ranjanvittal** [frenetic-lang/frenetic#451]
The run.sh file does not include the command line switches. 
When the command line switches(--vrel, --vtopo, etc) are added,
Updated run.sh is as follows.

#!/bin/bash

../../../frenetic.native virtual_cmd\
 --vpolicy  vpol.kat\
 --vrel  vrel.kat\
 --vtopo vtopo.kat\
  --ving-pol vingpol.kat\
  --ving ving.kat\
  --veg veg.kat\
  --ptopo ptopo.kat\
 --ping ping.kat\
  --peg peg.kat

for arg in "g_fabric" "g_pruned" "pg" "vg" "g_raw"
do
  echo $arg
  arg1="${arg}.dot"
  arg2="${arg}.png"
  dot -Tpng $arg1 > $arg2
done

I get the following error on running ./run.sh :
Uncaught exception:
  (Failure "continuation present, but no program counter field provided!")
after getting some partial output.

**Comment by mcanini** [comment]
@smolkaj Steffen, can you please check this issue?

**Comment by smolkaj** [comment]
Some refactoring must have messed this up. I cleaned things up a little in bcb477b. Should work now. Let me know.

**Comment by ranjanvittal** [comment]
@mcanini @smolkaj We are now able to run it using ./run.sh. After giving a certain output it is waiting which we expect is waiting for openflow switches to join it. We set the --openflow-port to 6633 and ran it with a sample topology with --controller=remote.. However that still shows that it cannot find a controller at port 6633. Any specific directives to help us in running it?

**Comment by smolkaj** [comment]
I'm clueless about how the controller stuff works. Maybe @jnfoster or @arjunguha can help.

**Comment by craig-riecke** [comment]
If I can jump in.  Currently the global and virtual compilers (virtual_cmd server) do not actually run an OpenFlow controller.  They only compile flow tables from the given files and output the result to stdout (similar to the --compile-server, but just from the command line).   

At some point, we'll connect the two but that part needs to be designed, implemented, etc.  Should that be sooner-rather-than-later?

**Comment by ranjanvittal** [comment]
Okay, then the script is still not giving the output as expected.

**Comment by jnfoster** [comment]
@ranjanvittal: can you provide some more detail? It's much easier for someone to jump in and help if they have a precise description of what you are running (just `run.sh`?) and the description of what you expect versus what you are seeing. 

Thanks,
N

**Comment by craig-riecke** [comment]
@ranjanvittal: I did fix the parameters in run.sh - that was my fault, so thanks for the tip.   However, if the script examples/virtual/diamond/run.sh seems to be hanging, I am seeing the same behavior on my machine.  (I waited for five minutes to complete and it hadn't, so it may just be taking a long time to run.  It does seem complex).

**Comment by smolkaj** [comment]
Do we know where it hangs? It might be the virtual compiler. I have noticed in the past that one of its components scales very poorly once the virtual network reaches a certain size. If that's the issue here, it shouldn't be hard to fix. I can take a look.

**Comment by ranjanvittal** [comment]
@craig-riecke yes i experienced the same issue. After printing mfin and mfout information, the script hangs. It doesnot give any further output even after it is run for about 15 minutes, I guess it might not be a performance issue.

**Comment by smolkaj** [comment]
I will take a look.

**Comment by smolkaj** [comment]
@ranjanvittal: Everything should work now.

**Comment by ranjanvittal** [comment]
Thanks! will check it out soon !
